### ISSUE TITLE
我把里面的文件放进git仓库下会报错

### ISSUE THREAD

**Issue by xuya227939** [ant-design/ant-design-pro#1446] opened 2018-05-07 02:33 UTC
Can't resolve 'components/ActiveChart' in '/Users/jiang/Desktop/WorkSpace/ant-pro-template/src/routes/Dashboard' 

报了这个错

![image](https://user-images.githubusercontent.com/16217324/39682384-20d1401e-51e2-11e8-8751-763341ea90c4.png)
zhe'shi这是我的文件结构，请帮忙看看。

**Comment by afc163** [comment] 2018-05-07 02:38
Duplicate of #1445

**Closed by afc163** 2018-05-07 02:38 UTC
