### ISSUE TITLE
yarn start/npm start takes forever

### ISSUE THREAD

**Issue by Chibaheit** [ant-design/ant-design-pro#1182] opened 2018-03-27 09:21 UTC
![0030-03-27 17 21 02](https://user-images.githubusercontent.com/6986642/37958500-474929c4-31e3-11e8-9edb-cee19c14f42f.jpg)
<img width="278" alt="screen shot 0030-03-27 at 17 21 13" src="https://user-images.githubusercontent.com/6986642/37958504-48c92646-31e3-11e8-8c28-bf16d8ccc12b.png">

**Comment by afc163** [comment] 2018-03-27 09:29
Duplicate of #1156

**Closed by afc163** 2018-03-27 09:29 UTC
