### ISSUE TITLE
异步加载菜单，构建符合需求的菜单格式？

### ISSUE THREAD

**Issue by dongtianqi** [ant-design/ant-design-pro#774] opened 2018-01-19 10:19 UTC
const list = [
        {
          name: '基础管理4444data',
          path: 'baseData',
          icon: 'check-circle-o',
          children: [
            {
              name: '考试数据管理',
              path: 'examData',
              model: 'exam',
              component: './routes/BaseData/ExamData',
            },
            {
              name: '准考证数据管理',
              path: 'licenseData',
              model: 'license',
              component: './routes/BaseData/LicensesData',
            },
          ],
        }];
      const arr = list.map((item) => {
        item.children.map((obj) => {
          obj.component = dynamicWrapper(app, [obj.model], () => import(obj.component));
          return obj;
        });
        return item;
      });
      const navData = [
        {
          component: dynamicWrapper(app, ['user', 'login'], () => import('./layouts/BasicLayout')),
          layout: 'BasicLayout',
          name: '首页', // for breadcrumb
          path: '/',
          children: list,
        }];_
报错：Uncaught (in promise) Error: Cannot find _module_ 'function DynamicComponent() {
//。。。。。。。

**Comment by afc163** [comment] 2018-01-19 12:05
Duplicate of #751

**Closed by afc163** 2018-01-19 12:05 UTC
