### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by anlia260** [ant-design/ant-design-pro#302] opened 2017-11-27 09:34 UTC
npm ERR! git rev-list -n1 fix-babel-resolve: fatal: ambiguous argument 'fix-babel-resolve': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 fix-babel-resolve: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 fix-babel-resolve: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 fix-babel-resolve:
npm ERR! git rev-list -n1 fix-babel-resolve: fatal: ambiguous argument 'fix-babel-resolve': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 fix-babel-resolve: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 fix-babel-resolve: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 fix-babel-resolve:
npm ERR! git clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345: Cloning into bare repository 'C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345'...
npm ERR! git clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345:
npm ERR! git clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345: and the repository exists.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.2.0
npm ERR! npm  v4.0.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:afc163/roadhog-api-doc.git C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345
npm ERR! Cloning into bare repository 'C:\Users\Fed\AppData\Roaming\npm-cache\_git-remotes\git-github-com-afc163-roadhog-api-doc-git-fix-babel-resolve-020a5345'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by afc163** [comment] 2017-11-27 09:42
Duplicate of #301

**Closed by afc163** 2017-11-27 09:42 UTC
