### ISSUE TITLE
用IE11打开localhost:8000报错

### ISSUE THREAD

**Issue by LeonSheng** [ant-design/ant-design-pro#452] opened 2017-12-16 16:08 UTC
![_20171217000454](https://user-images.githubusercontent.com/18523719/34072224-43efe552-e2be-11e7-9926-67b1730bb66a.png)
![_20171217000748](https://user-images.githubusercontent.com/18523719/34072230-5a01decc-e2be-11e7-8ca3-c1dd3e1db856.png)

**Comment by afc163** [comment] 2017-12-16 17:25
Duplicate of #210

**Closed by afc163** 2017-12-16 17:25 UTC
