### ISSUE TITLE
fix-babel-resolve missed

### ISSUE THREAD

**Issue by suntopo** [ant-design/ant-design-pro#303] opened 2017-11-27 09:36 UTC
⠼ Auto installing...npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout fix-babel-resolve
npm ERR! error: pathspec 'fix-babel-resolve' did not match any file(s) known to git.
npm ERR!

**Comment by afc163** [comment] 2017-11-27 09:42
Duplicate of #301

**Closed by afc163** 2017-11-27 09:42 UTC
