### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by wangzj141** [ant-design/ant-design-pro#2063] opened 2018-08-28 09:45 UTC
npm start

![image](https://user-images.githubusercontent.com/5604075/44715334-1d925a80-aaea-11e8-9536-7533ac199f78.png)

**Comment by ybning** [comment] 2018-08-28 11:33
Duplicate of #2043

**Comment by 18830438187** [comment] 2018-08-29 09:35
遇到一样的问题

**Closed** 2018-09-03 05:46 UTC
